const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  console.log("Compiling contracts...");
  await hre.run("compile");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // Deploy ProofOfReserves
  const Proof = await hre.ethers.getContractFactory("ProofOfReserves");
  const proof = await Proof.deploy();
  await proof.waitForDeployment();
  const proofAddress = await proof.getAddress();
  console.log("ProofOfReserves deployed to:", proofAddress);

  // Deploy GovernanceDAO
  const Governance = await hre.ethers.getContractFactory("GovernanceDAO");
  const governance = await Governance.deploy();
  await governance.waitForDeployment();
  const governanceAddress = await governance.getAddress();
  console.log("GovernanceDAO deployed to:", governanceAddress);

  // Write addresses to integration/.env (workspace root -> integration folder)
  const envPath = path.resolve(__dirname, "..", "..", "integration", ".env");
  const contents = [];
  contents.push("# Auto-generated by blockchain_layer/scripts/deploy_all.cjs");
  contents.push(`RPC_URL=http://127.0.0.1:8545`);
  contents.push(`CONTRACT_ADDRESS=${proofAddress}`);
  contents.push(`DAO_CONTRACT_ADDRESS=${governanceAddress}`);
  contents.push("# MERKLE_ROOT=\n# MERKLE_PROOF=[]\n# MERKLE_LEAF=\n# TOTAL_RESERVES=\n");

  try {
    fs.writeFileSync(envPath, contents.join("\n"));
    console.log(`Wrote addresses to ${envPath}`);
  } catch (err) {
    console.warn("Failed to write integration .env (does integration folder exist?):", err.message);
  }

  // Optionally copy artifacts into a stable path for integration/backend if desired
  // For now we only provide the addresses; integration scripts should read artifacts
  // from the Hardhat artifacts directory or your checked-in copies.
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
